### ISSUE TITLE
Implement SRV records for swarm services

### ISSUE THREAD

**Issue by sanimej** [docker/libnetwork#1362]
Implement SRV records for swarm services . 
[libnetwork #1163] (https://github.com/docker/libnetwork/pull/1163) added changes in the DNS server to handle the SRV query. But the service DB update based on swarm service life cycle is not integrated yet.

**Comment by sandekar** [comment]
Is there a chance that Docker Swarm will publish SRV records? We could really use that extra host information in them.

**Why do I ask ?**
In the company where I work, we are building an infrastructure consisted of [Prometheus ](https://prometheus.io/) + various exporters deployed as global Swarm services (Node exporter, cAdvisor etc) to collect metrics about our hosts and containers. In the Prometheus configuration we _scrape_ those exporters using [DNS resolution](https://prometheus.io/docs/operating/configuration/#<dns_sd_config>) to `tasks.<service-name>`. 

But because Swarm publishes A/AAAA records we get only the IP addresses of exporter containers. If some exporter service is restarted on some host (or the host is restarted) or deployed to a new one, its IP address will be different and we cannot correctly consume the metric data by it.

This makes it difficult to render metric data by hosts and even more difficult to trace problems related to a specific host/service, because we got to trace by container IP address where the concrete exporter's service is deployed.

Prometheus supports SRV records and exposes a label called `__meta_dns_name` which could be used to relabel the metric's instance, making it possible to include the hostname in the scraped metrics.

**Comment by johan-adriaans** [comment]
+1 for this. My use case is using the new Haproxy 1.8.0 feature that automatically configures its servers based on SRV records:

> DNS SRV records (Olivier Houchard) : in order to go a bit further with DNS resolution, SRV records were implemented. The address, port and weight attributes will be applied to servers. New servers are automatically added provided there are enough available templates, and servers which disappear are automatically removed from the farm. By combining server templates and SRV records, it is now trivial to perform service discovery.

https://www.mail-archive.com/haproxy@formilux.org/msg28004.html

**Comment by xenoterracide** [comment]
+1, would want this regardless of swarm, just basic network

**Comment by blop** [comment]
More information about potential use with HAProxy here : https://www.haproxy.com/blog/dns-service-discovery-haproxy/

**Comment by ddebroy** [comment]
I wanted to clarify something about the HAProxy use case mentioned by @blop and @johan-adriaans: are you launching services using swarm in a cluster but want to use HAProxy to perform the load balancing directly on the swarm task containers rather than go through swarm's IPVS based load balancing?

@xenoterracide I am not sure I understand what you are referring to as "just basic network"? My understanding of this issue is to implement support for DNS SRV queries for a swarm service (with the answer pointing to the service's task containers). Are you looking for SRV support against individual container names (launched directly using `docker run`)?

**Comment by xenoterracide** [comment]
"just basic network" e.g. if I'm running docker-compose (or run), no swarm, in this way I can simply run the same cluster locally.

> Are you looking for SRV support against individual container names (launched directly using docker run)?

I could see name or alias, really specifically the dns alias is the best match for me, as I name that specifically so it's consistent regardless.

> you launching services using swarm in a cluster but want to use HAProxy to perform the load balancing directly on the swarm task containers rather than go through swarm's IPVS based load balancing

also yes, but for other things in addition to load balancing, such as TLS termination, caching,http header addition/translation ) (I didn't even know swarm had a load balancer until 10s ago)

here's one of my compose configurations, I would expect whether in swarm or or compose, or if I started them with run, that master and slave, both which have EXPOSE 8080 that I would be able to run a query like `_http-alt._tcp.dex.master`, this particulary haproxy will be responisble for both tls termination and load balancing, I have another though that needs to send updated headers, 'cause cloudfront.

```
version: "3"
services:
  master:
    build: ./etc/docker/dex
    image: 927476265057.dkr.ecr.us-east-1.amazonaws.com/dex/dex:latest
    ports:
      - 8001:8000
      - 1098:1098
    volumes:
      - ./dex-ui/target:/mnt/ui
    environment:
      - JMX_PORT=1098
      - HIBERNATE_SEARCH_DEFAULT_WORKER_BACKEND=jgroupsMaster
    networks:
      cluster:
        aliases:
          - dex.master
  slave:
    build: ./etc/docker/dex
    image: 927476265057.dkr.ecr.us-east-1.amazonaws.com/dex/dex:latest
    ports:
      - 8002:8000
      - 1099:1099
    volumes:
      - ./dex-ui/target:/mnt/ui
    environment:
      - JMX_PORT=1099
      - HIBERNATE_SEARCH_DEFAULT_WORKER_BACKEND=jgroupsSlave
    networks:
      cluster:
        aliases:
          - dex.slave
  lb:
    build:
        context: etc/docker/load-balancer
        args:
        - CONFIG=haproxy.cfg
    ports:
    - 80:80
    - 443:443
    networks:
      cluster:
```
