### ISSUE TITLE
Docker reports "ipv4 pool is empty" - but it is not

### ISSUE THREAD

**Issue by rayjohnson** [docker/libnetwork#1942]
I have a compose file with a networks section like this:

```
networks:
  front:
    ipam:
      driver: qnet
      options: 
        iface: eth1
  back:
    driver: customer-driver-1
    internal: true
    ipam:
      driver: default
```

When I do my docker-compose up - I get this:
```
Creating network "mywordpress_front" with the default driver
ERROR: ipv4 pool is empty
DESKTOP-8O0TNFC:mywordpress
```

However, I know there are plenty of IPs available.  Also, this works fine when I create the network via docker command line:
`docker network create -d qnet --ipam-driver=qnet --ipam-opt=iface=eth1 qnet-dhcp-eth1
`
I'm fairly certain I have the compose syntax correct.  Why am I getting this error and what does it mean?

ray
