### ISSUE TITLE
Chrome and Postman cannot connect to container through localhost but curl can

### ISSUE THREAD

**Issue by Dauto98** [docker/libnetwork#2252]
**Description**
When I launch a container and want to connect to the app inside it, e.g. connect to elastic kibana container through `http://localhost:5601`, the request run indefinitely and return `took too long to respond` after a long time. The same problem happens in postman, but curl and any cmd like ping, nc work perfectly fine.
This problem also happens to elasticsearch and kong API gateway container in my lap, so I think this is not related specifically to the application inside the container

**Steps to reproduce the issue**
1. Create `docker-compose.yml`
```
version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasticStack
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data/
        volume:
          nocopy: true
    environment:
      discovery.type: "single-node"
      TAKE_FILE_OWNERSHIP: "true"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5601:5601"
    networks:
      - elasticStack
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"

networks:
  elasticStack:

volumes:
  elasticsearch:
```
2. deploy the stack
3. when kibana is up, connect to `http://localhost:5601`
- In chrome and postman, the connection run indefinitely, or return `... took too long to respond`
- Run `curl --url http://localhost:5601`, return 200 response from kibana
- Use `http://localhost:9200` to connect to elasticsearch also has the same problem
- If I replace localhost with 127.0.0.1 `(http://127.0.0.1:5601)`, then everything works well (chrome got 200 response)
- If I run `docker exec -it <container name> bash` and try `curl http://localhost:5601` inside container, I also get 200 response
- If I take Peers.IP from `docker network inspect elasticstack_elasticStack`, which is 192.168.31.116 in my case, it also hangs indefinitely like localhost

**Expected result**
Able to connect to container through localhost

**Additional information**
- OS: Ubuntu 16.04 LTS
- Docker version 18.06.0-ce, build 0ffa825

- Output from `docker network inspect elasticstack_elasticStack`
```
[
    {
        "Name": "elasticstack_elasticStack",
        "Id": "yis9p0u0x8gl1e93bwik32ykh",
        "Created": "2018-08-16T14:49:09.459047334+07:00",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.1.0/24",
                    "Gateway": "10.0.1.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "64e7b78a3fc280281b9b50ddcc68ae6b785cfeacd94025b4ffaeea9751092522": {
                "Name": "elasticstack_elasticsearch.1.kahec8xp1nedu8n48dzs6yukj",
                "EndpointID": "d1992b17c761458dbd81e574bfc14935e919cd453d9e2bfce45e32ef80aebcb1",
                "MacAddress": "02:42:0a:00:01:04",
                "IPv4Address": "10.0.1.4/24",
                "IPv6Address": ""
            },
            "ff821df8aafd170675f9f9803b9057fba0268b7df7b738571dc814907a3f10a4": {
                "Name": "elasticstack_kibana.1.ulje0alsjxqmt7im6efjskw4j",
                "EndpointID": "4c030be76c392f7901fcd4ccf1413be04a952da513266aec98a076e143711d35",
                "MacAddress": "02:42:0a:00:01:06",
                "IPv4Address": "10.0.1.6/24",
                "IPv6Address": ""
            },
            "lb-elasticstack_elasticStack": {
                "Name": "elasticstack_elasticStack-endpoint",
                "EndpointID": "b029c9ec53ca88a189a789101e6ae31c2b222fc8d23711f5ceb62a2e6f886112",
                "MacAddress": "02:42:0a:00:01:02",
                "IPv4Address": "10.0.1.2/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4098"
        },
        "Labels": {
            "com.docker.stack.namespace": "elasticstack"
        },
        "Peers": [
            {
                "Name": "6b3933df975f",
                "IP": "192.168.31.116"
            }
        ]
    }
]
```
- My current server is openresty (openresty/1.13.6.2) but using apache (Apache/2.4.18) get the same problem
- My `/user/local/openresty/nginx/conf/nginx.conf` file:
```

#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }

    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}
```
